version: '3'

services:
   mariadb:
     image: mariadb
     restart: always
     ports:
       - 3305:3306
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     volumes:
       - /var/lib/mysql

   mariadb2:
     image: mariadb
     restart: always
     ports:
       - 3310:3306
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     volumes:
       - /var/lib/mysql

   wordpress:
     image: wordpress:latest
     ports:
       - 8090:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: mariadb
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - /Documents/WordPress/Site-A:/var/www/html

   wordpress2:
     image: wordpress:latest
     ports:
       - 8085:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: mariadb2
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - /Documents/WordPress/Site-B:/var/www/html

   adminer:
     image: adminer
     restart: always
     ports:
       - 8081:8080

   proxymanager:
     image: 'jc21/nginx-proxy-manager:latest'
     container_name: NginxProxyManager
     restart: unless-stopped
     ports:
       - '80:80'
       - '81:81'
       - '443:443'
     volumes:
       - ./data:/data
       - ./letsencrypt:/etc/letsencrypt
